name: build_task2

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
     - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
     - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
     - uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 3.0.x
     - run: pwd
     - run: ls -la
     - run: cd /usr/share/dotnet/sdk
     - run: ls -la
     - name: Build
       run: dotnet build 
       working-directory: Client

